apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/wakabaseisei/ms-kubernetes.git
      revision: HEAD
      directories:
      - path: services/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: dev
      source:
        repoURL: https://github.com/wakabaseisei/ms-kubernetes.git
        targetRevision: main
        path: '{{path}}'
        helm:
          releaseName: '{{path.basename}}'
          valueFiles:
          - "values/{{path.basename}}/dev/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
