replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
image:
  repository: 148761642613.dkr.ecr.ap-northeast-1.amazonaws.com/api-front
  tag: "dev-20250222-141648-5da68cd"
autoscaling:
  enabled: false
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  paths:
    - path: /
      pathType: Prefix
  tls: []
serviceAccount:
  name: api-front
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::148761642613:role/irsa
