replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
image:
  repository: 148761642613.dkr.ecr.ap-northeast-1.amazonaws.com/api-front
  tag: "dev-20250413-121100-1909462"
autoscaling:
  enabled: false
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
  paths:
    - path: /
      pathType: Prefix
  tls: []
serviceAccount:
  name: api-front
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::148761642613:role/irsa-api-front

env:
  - name: AWS_REGION
    value: "ap-northeast-1"
  - name: DB_HOST
    value: "api-front.cluster-ct8g8ao0ofg2.ap-northeast-1.rds.amazonaws.com"
  - name: DB_NAME
    value: "ApiFront"
  - name: DB_USER
    value: "api-front"
  - name: DB_PORT
    value: "3306"