replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
image:
  repository: 148761642613.dkr.ecr.ap-northeast-1.amazonaws.com/api-front
  tag: "dev-20250501-154359-ef54023"
autoscaling:
  enabled: false
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
  paths:
    - path: /
      pathType: Prefix
  tls: []

env:
  - name: USER_SERVICE_ENDPOINT
    value: "http://ms-user.ms-user.svc.cluster.local:8080"
